### ISSUE TITLE
Status indicators

### ISSUE THREAD

**Issue by funwhilelost** [faulker/WallabagIt#9]
My self-hosted Wallabag takes a while to respond.  It would be great to see some status indicators while the article list is being loaded in the main pane.

It would also be nice to get a real error message inside the pane.  When my host went down for a bit I couldn't tell what was going on - just a blank window...

Thanks for your work on this extension!

**Comment by funwhilelost** [comment]
Finally got to the bottom of it: I put the wrong user in the options.  The token call works for the API but the user was not yet validated (you have to confirm a new user via email).  It might be nice to add this check to the options screen.

**Comment by faulker** [comment]
@funwhilelost 
I'll look into adding/adjusting the extension to handle status check errors.

I agree there needs to be some kind of indicator when the article list is loading/adding/refreshing/etc and will try and add one soon.

Thanks for the feedback!
